#!/usr/bin/env bash
# a Bash script that transfers a file from our client to a server:
# Args:
#    PATH_TO_FILE: The path to the file to be transferred
#    IP: The IP of the server we want to transfer the file to
#    USERNAME: The username scp connects with
#    PATH_TO_SSH_KEY: The path to the SSH private key that scp uses


if [ $# -ne 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi
i
PATH_TO_FILE=$1
IP=$2
USERNAME=$3
PATH_TO_SSH_KEY=$4

scp -i "$PATH_TO_SSH_KEY" "$PATH_TO_FILE" "$USERNAME"@"$IP":~/
