#!/usr/bin/env bash
# a Bash script that configures a new Ubuntu machine

sudo apt-get -y update
sudo apt-get -y install nginx
sudo sh -c 'echo "Hello World!" > /var/www/html/index.html'
service nginx start
