#!/usr/bin/env bash
# a Bash script that configures a new Ubuntu machine
new_config="server {
    listen 80;
    server_name _;
    location /redirect_me {
        return 301 https://example.com/new_page;
    }
}"
apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
sed -i "/server_name _;/a $new_config" /etc/nginx/sites-enabled/default
service nginx start
