#!/usr/bin/env bash
# a Bash script that displays all active IPv4 IPs on the machine it’s executed on.

# Get all active IPv4 addresses
active_ips=$(ip -4 addr show | grep inet | awk '{print $2}' | cut -d'/' -f1)

# Print the active IPv4 addresses
echo "$active_ips"
