#!/usr/bin/env bash
sudo echo "server {
    listen 80;
    server_name 54.164.5.211;

    location /airbnb-onepage/ {
        proxy_pass http://127.0.0.1:5000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}" > /etc/nginx/sites-available/flask_app.confg
sudo ln -s /etc/nginx/sites-available/flask_app.confg /etc/nginx/sites-enabled/
sudo nginx -t
sudo service nginx restart
